### PR TITLE
New events 3.1.6

### PR DESCRIPTION
**Pull request by Oyabun1**
New template events for 3.1.6

### CODE REVIEW

**Comment by Oyabun1** [comment]
Just close this. I was just playing around and completely mucked it up.

**Comment by eeemarv** [comment]
Is it not good? 
I see there are no newline endings in the files. Maybe you need to change a setting in your editor?

**Comment by Oyabun1** [comment]
That was part of the problem. Somehow the setting for using Unix EOL for new pages had changed to Windows EOL.

**Comment by marttiphpbb** [comment]
Are there any other problems then apart from the line endings?

**Comment by Oyabun1** [comment]
There were some ACP events missed and added but it was mostly the line endings. 

I hate Git. I thought I had fixed it and amended the commit but then realised I had previously pushed to the wrong repository. Deleted that branch and tried again, but it still doesn't seem to be right.

**Comment by marttiphpbb** [comment]
Thanks. Merged. I've seen there are still incorrect line endings. I will run the repo through git-stripspace to clean it up.

**Pull request merged**
